services:
  web:
    image: nas415/video_crafter1:latest
    env_file:
      - .env
    command: >
      sh -c "
        python3.10 manage.py makemigrations &&
        python3.10 manage.py migrate &&
        python3.10 manage.py runserver 0.0.0.0:7732
      "
    volumes:
      - .:/app
    ports:
      - "7732:7732"
