# Generated by Django 4.2.16 on 2024-11-25 11:58

from django.db import migrations, models
import django.db.models.deletion
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('vidoe_text', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='timestamp_end',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='timestamp_start',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='video_file_path',
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='slide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SubClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtittle', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to=mainapps.vidoe_text.models.text_clip_upload_path)),
                ('main_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclips', to='vidoe_text.textlinevideoclip')),
                ('video_clip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips_used_for', to='video.videoclip')),
            ],
        ),
    ]
