# Generated by Django 4.2.16 on 2024-11-25 19:15

from django.db import migrations, models
import django.db.models.deletion
import mainapps.vidoe_text.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('vidoe_text', '0002_remove_textlinevideoclip_timestamp_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='slide',
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='timestamp_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='timestamp_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='video_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='video.videoclip'),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='video_file_path',
            field=models.FileField(blank=True, null=True, upload_to=mainapps.vidoe_text.models.text_clip_upload_path),
        ),
        migrations.DeleteModel(
            name='SubClip',
        ),
    ]
