# Generated by Django 4.2.16 on 2024-12-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0004_remove_textlinevideoclip_timestamp_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlinevideoclip',
            name='total_clip',
            field=models.IntegerField(default=1),
        ),
    ]
