# Generated by Django 4.2.16 on 2024-12-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0005_textlinevideoclip_total_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='subclips_text_file',
            field=models.FileField(blank=True, null=True, upload_to='subclips_text_files/'),
        ),
    ]
