# Generated by Django 4.2.16 on 2024-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0006_textfile_subclips_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfile',
            name='generated_subclips_srt',
            field=models.FileField(blank=True, null=True, upload_to='generated_subclips_srt/'),
        ),
    ]
