# Generated by Django 4.2.16 on 2024-12-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0007_textfile_generated_subclips_srt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclip',
            name='end',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='subclip',
            name='start',
            field=models.DecimalField(blank=True, decimal_places=6, default=0.1, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='textlinevideoclip',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='text_clip_upload_videos/'),
        ),
    ]
