# Generated by Django 4.2.16 on 2024-12-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0008_subclip_end_subclip_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textlinevideoclip',
            name='total_clip',
        ),
    ]
