# Generated by Django 4.2.16 on 2024-12-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0009_remove_textlinevideoclip_total_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlinevideoclip',
            name='remaining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
