# Generated by Django 4.2.16 on 2024-12-27 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vidoe_text', '0010_textlinevideoclip_remaining'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subclip',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='subclip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
