# Generated by Django 4.2.16 on 2024-10-26 21:38

from django.db import migrations, models
import django.db.models.deletion
import mainapps.audio.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("vidoe_text", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "music",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mainapps.audio.models.bg_music_file_upload_path,
                    ),
                ),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                (
                    "bg_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        default=0.1,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "text_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="background_musics",
                        to="vidoe_text.textfile",
                    ),
                ),
            ],
        ),
    ]
